print("What is ur name?")
nameUser = input()
print("How old r u?")
ageUser = input()
print("Where r u live?")
cityUser = input()
print("This is {0}.".format(nameUser))
print("It is {0}.".format(ageUser))
print("S(he) live in {0}.".format(cityUser))
